AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: 'The environment for the deployment (dev or prod)'
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: "Must be either 'dev' or 'prod'."
  WraithwatchLambdaAtEdgeBucketName:
    Type: String
    Default: 'wraithwatch-lambda-at-edge'
    Description: 'S3 bucket for storing wraithwatch-lambda-at-edge lambda deployment'

Resources:
  WraithwatchLambdaAtEdgeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${WraithwatchLambdaAtEdgeBucketName}-${Environment}'

Outputs:
  WraithwatchLambdaAtEdgeBucketName:
    Value: !Ref WraithwatchLambdaAtEdgeBucket
    Export:
      Name: !Sub 'WraithwatchLambdaAtEdgeBucketName-${Environment}'
