AWSTemplateFormatVersion: "2010-09-09"



Resources:
  WraithwatchChatBotBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "wraithwatch-chat-bot"

Outputs:
  WraithwatchChatBotBucketName:
    Value: !Ref WraithwatchChatBotBucket
    Export:
      Name: "WraithwatchChatBotBucketName"
