AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3Key:
    Type: String
    Description: 'S3 key for the lambda deployment package'

Resources:


  WraithwatchLambdaAtEdgeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'wraithwatch-lambda-at-edge'
      Runtime: nodejs20.x
      Handler: index.handler
      Role:
        Fn::ImportValue: 'WraithwatchLambdaAtEdgeExecutionRoleArn'
      Code:
        S3Bucket:
          Fn::ImportValue: 'WraithwatchLambdaAtEdgeBucketName'
        S3Key: !Ref S3Key
      Timeout: 30
      MemorySize: 128

Outputs:
  WraithwatchLambdaAtEdgeFunctionArn:
    Value: !GetAtt WraithwatchLambdaAtEdgeFunction.Arn
    Description: 'Lambda function ARN'
    Export:
      Name: 'WraithwatchLambdaAtEdgeFunctionArn'
