name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
      NEXT_PUBLIC_WEBSOCKET_URL: ${{ secrets.WEBSOCKET_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Lint Code
        run: |
          yarn lint

      - name: Run Frontend Tests
        run: |
          yarn workspace @wraithwatch/frontend test

      - name: Frontend Coverage Threshold Check
        run: |
          cd apps/frontend
          if [[ $(grep "Statements" coverage/lcov-report/index.html | awk '{print $4}' | tr -d '%') -lt 70 ]]; then
            echo "Frontend code coverage is below threshold. Please update test coverage and try again."
            exit 1
          fi

      - name: Build Frontend
        run: |
          yarn workspace @wraithwatch/frontend build

      - name: Copy Sitemap and Robots Files
        run: |
          cp apps/frontend/public/sitemap.xml apps/frontend/out/
          cp apps/frontend/public/robots.txt apps/frontend/out/
          cp apps/frontend/public/sitemap-0.xml apps/frontend/out/

      - name: Archive Build Output
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: apps/frontend/out
          retention-days: 1

  deploy:
    name: Deploy to S3
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync frontend-build/ s3://wraithwatch-frontend/ --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2BS8G6FZ8VAXH \
            --paths "/*"

  live_tests:
    name: Run Live Tests (E2E + Lighthouse)
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Wait for Deployment
        run: |
          echo "Waiting for deployment to propagate and CloudFront cache to invalidate..."
          sleep 60

      - name: Run E2E Tests Against Live Site
        run: |
          cd apps/frontend
          npx cypress run --config baseUrl=https://www.wraithwatch-demo.com

      - name: Run Lighthouse Tests Against Live Site
        id: lighthouse
        run: |
          cd apps/frontend
          NODE_ENV=production npx lhci autorun --chrome-flags="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LH_TOKEN }}
